### ISSUE TITLE
P2P implementation

### ISSUE THREAD

**Issue by tkzcfc** [cs3103-1819s1-g4/cs3103_p2p#34]
Hello, I've recently written a P2P for online games, but sometimes it doesn't work (sometimes it does). Now it's only possible for players to succeed on the same LAN. I wonder when the P2P communication for this project will be completed. I would like to refer to your code. Or can you recommend some reference materials for me?

**Comment by jasmoon** [comment]
There are various ways to traverse NAT, one of them is through use of STUN servers (refer to RFC5389) which is recommended by our prof. There are other methods such as UDP hole punching which I am not familiar with and unable to advice which method should u use for your P2P online game.

**Comment by tkzcfc** [comment]
OK, thank you. I will try it.
